app/src/Entity/BankTransfer.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BankTransferRepository")
 */
class BankTransfer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Bank_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $IBAN;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $BIC;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $account_owner;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bankTransfers")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBankName(): ?string
    {
        return $this->Bank_name;
    }

    public function setBankName(string $Bank_name): self
    {
        $this->Bank_name = $Bank_name;

        return $this;
    }

    public function getIBAN(): ?string
    {
        return $this->IBAN;
    }

    public function setIBAN(string $IBAN): self
    {
        $this->IBAN = $IBAN;

        return $this;
    }

    public function getBIC(): ?string
    {
        return $this->BIC;
    }

    public function setBIC(string $BIC): self
    {
        $this->BIC = $BIC;

        return $this;
    }

    public function getAccountOwner(): ?string
    {
        return $this->account_owner;
    }

    public function setAccountOwner(string $account_owner): self
    {
        $this->account_owner = $account_owner;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

app/src/Entity/CreditCard.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CreditCardRepository")
 */
class CreditCard
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number;

    /**
     * @ORM\Column(type="datetime")
     */
    private $validity;

    /**
     * @ORM\Column(type="integer")
     */
    private $security_code;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="creditCards")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(int $number): string
    {
        $this->number = $number;

        return $this;
    }

    public function getValidity(): ?\DateTimeInterface
    {
        return $this->validity;
    }

    public function setValidity(\DateTimeInterface $validity): self
    {
        $this->validity = $validity;

        return $this;
    }

    public function getSecurityCode(): ?int
    {
        return $this->security_code;
    }

    public function setSecurityCode(int $security_code): self
    {
        $this->security_code = $security_code;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

app/src/Controller/PaymentController.php
<?php


namespace App\Controller;

use App\Repository\BankTransferRepository;
use App\Repository\CreditCardRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PaymentController extends AbstractController
{

    /**
     * @Route("/profile/payment", name="profile.payment.index")
     * @param CreditCardRepository $creditCardRepository
     * @param BankTransferRepository $bankTransferRepository
     * @return Response
     */
    public function index(CreditCardRepository $creditCardRepository, BankTransferRepository $bankTransferRepository): Response
    {
        $user = $this->getUser();
        $creditCards = $creditCardRepository->findAllJoinedToUser($user->getId());
        $bankTransfers = $bankTransferRepository->findAllJoinedToUser($user->getId());

        return $this->render('profile/payment/index.html.twig', [
            'user' => $user,
            'creditCards' => $creditCards,
            'bankTransfers' => $bankTransfers
        ]);
    }
}

app/templates/profile/payment/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Mes Moyens de Payements ' %}

{% block body %}
    <div class="container mt-3">
    <h1>Mes Moyens de Payements </h1>
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus imperdiet porttitor justo. Donec ac lorem
        neque. Suspendisse vel urna faucibus, fermentum lacus ut, efficitur ex. Aliquam rhoncus tellus in pulvinar
        faucibus. Curabitur tempor mollis magna, ut volutpat elit blandit ut. Donec imperdiet at lectus vitae
        mattis. Duis et congue magna. Vestibulum posuere tempus pretium. Aliquam a facilisis tortor. Vestibulum
        imperdiet viverra lorem, non fringilla mauris blandit sit amet. Suspendisse finibus placerat velit, id
        sodales nibh suscipit at. Morbi et tortor orci.
    </p>

    <div class="row">
        <div class="col-md-6">
            <h2>Cartes de Crédit</h2>

            {% for creditCard in creditCards %}
                <div class="element">

                    <h4>N°{{ loop.revindex }}</h4>
                    <table class="table table-striped">
                        <tr>
                            <td>Nom</td>
                            <td>{{ creditCard.name }}</td>
                        </tr>
                        <tr>
                            <td>Numéro de carte</td>
                            <td>{{ creditCard.number }}</td>
                        </tr>
                        <tr>
                            <td>Date de validité</td>
                            <td>{{ creditCard.validity |date('Y-m-d') }}</td>
                        </tr>
                        <tr>
                            <td>Code de Sécurité</td>
                            <td> {{ creditCard.securityCode }}</td>
                        </tr>
                    </table>
                </div>

            {% endfor %}
        </div>

        <div class="col-md-6">
            <h2>Payements Bancaires</h2>

            {% for bankTransfer in bankTransfers %}
                <div class="element">


                    <h4>N°{{ loop.revindex }}</h4>
                    <table class="table table-striped">
                        <tr>
                            <td>Nom de la Banque</td>
                            <td>{{ bankTransfer.BankName }}</td>
                        </tr>
                        <tr>
                            <td>IBAN</td>
                            <td>{{ bankTransfer.IBAN }}</td>
                        </tr>
                        <tr>
                            <td>BIC</td>
                            <td>{{ bankTransfer.BIC }}</td>
                        </tr>
                        <tr>
                            <td>Nom du Propriétaire</td>
                            <td> {{ bankTransfer.accountOwner }}</td>
                        </tr>
                    </table>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/profile/payment/show.html.twig
{% extends 'base.html.twig' %}

{% block title offer.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <img src="{{ asset('img/square-placeholder.jpg') }}">
                </div>
                <div class="col-md-4">
                    <h1>{{ offer.title }}</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <p>
            {{ offer.description | nl2br }}
        </p>
    </div>

    {% if offer.modalities %}
        <div class="container">

            <h2>Nos modalités d'inscription</h2>

            <div class="row flex">
                {% for modality in  offer.modalities %}
                    <div class="col-4">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ modality.title }}</h5>
                                <p class="card-text">Soit {{ modality.price }}€ par mois</p>
                                <a href="#" class="btn btn-primary">S'abonner</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% else %}
        <h2>Vous n'avez pas encore d'abonnements !</h2>
    {% endif %}
{% endblock %}