app/src/Entity/Subscription.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SubscriptionRepository")
 */
class Subscription
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $renewal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="subscriptions")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Offer", inversedBy="subscriptions")
     */
    private $offer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $payment_option;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $payment_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getRenewal(): ?bool
    {
        return $this->renewal;
    }

    public function setRenewal(bool $renewal): self
    {
        $this->renewal = $renewal;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getOffer(): ?Offer
    {
        return $this->offer;
    }

    public function setOffer(?Offer $offer): self
    {
        $this->offer = $offer;

        return $this;
    }

    public function getPaymentOption(): ?string
    {
        return $this->payment_option;
    }

    public function setPaymentOption(string $payment_option): self
    {
        $this->payment_option = $payment_option;

        return $this;
    }

    public function getPaymentId(): ?int
    {
        return $this->payment_id;
    }

    public function setPaymentId(?int $payment_id): self
    {
        $this->payment_id = $payment_id;

        return $this;
    }
}

app/src/Form/SubscriptionType.php
<?php

namespace App\Form;

use App\Entity\Offer;
use App\Entity\Subscription;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SubscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('created_at')
            ->add('start_date')
            ->add('end_date')
            ->add('renewal')
            ->add('status')
            ->add('payment_option')
            ->add('payment_id')
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'username',
            ])
            ->add('offer', EntityType::class, [
                'class' => Offer::class,
                'choice_label' => 'title',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Subscription::class,
        ]);
    }
}

app/src/Controller/SubscriptionController.php
<?php


namespace App\Controller;

use App\Repository\SubscriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class SubscriptionController extends AbstractController
{
    /**
     * @Route("/profile/subscriptions", name="profile.subscription.index")
     * @param SubscriptionRepository $subscriptionRepository
     * @return Response
     */
    public function index(SubscriptionRepository $subscriptionRepository): Response
    {
        $user = $this->getUser();
        $subscriptions = $subscriptionRepository->findAllJoinedToUser($user->getId());

        return $this->render('profile/subscription/index.html.twig', [
            'user' => $user,
            'subscriptions' => $subscriptions
        ]);
    }
}

app/templates/profile/subscription/_subscription.html.twig
<div class="element">

    <h4>Abonnement N°{{ loop.revindex }} </h4>
    <table class="table table-striped">
        <tr>
            <td>Date de Création</td>
            <td>{{ subscription.createdAt |date('Y-m-d') }}</td>
        </tr>
        <tr>
            <td>Date de Début</td>
            <td>{{ subscription.startdate |date('Y-m-d') }}</td>
        </tr>
        <tr>
            <td>Date de Fin</td>
            <td>{{ subscription.enddate |date('Y-m-d') }}</td>
        </tr>
        <tr>
            <td>Est renouvelée</td>
            <td> {% if subscription.renewal %}
                    Oui
                {% else %}
                    Non
                {% endif %}</td>
        </tr>
        <tr>
            <td>Statut</td>
            <td>{{ subscription.status }}</td>
        </tr>
        <tr>
            <td>Titre de l'offre</td>
            <td>{{ subscription.offer.title }}</td>
        </tr>
        <tr>
            <td>Moyen de Payement</td>
            <td>{{ subscription.paymentOption }}</td>
        </tr>
        <tr>
            <td>Identifiant du Moyen de Payement</td>
            <td>{{ subscription.paymentId }}</td>
        </tr>
    </table>
</div>

app/templates/profile/subscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Mes Abonnement' %}

{% block body %}
    <div class="container mt-3">
        <h1>Mes Abonnement</h1>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus imperdiet porttitor justo. Donec ac lorem
            neque. Suspendisse vel urna faucibus, fermentum lacus ut, efficitur ex. Aliquam rhoncus tellus in pulvinar
            faucibus. Curabitur tempor mollis magna, ut volutpat elit blandit ut. Donec imperdiet at lectus vitae
            mattis. Duis et congue magna. Vestibulum posuere tempus pretium. Aliquam a facilisis tortor. Vestibulum
            imperdiet viverra lorem, non fringilla mauris blandit sit amet. Suspendisse finibus placerat velit, id
            sodales nibh suscipit at. Morbi et tortor orci.
        </p>
        <div class="row">
            {% for subscription in subscriptions %}
                <div class="col-md-6">
                    {% include 'profile/subscription/_subscription.html.twig' %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/profile/subscription/show.html.twig
{% extends 'base.html.twig' %}

{% block title offer.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <img src="{{ asset('img/square-placeholder.jpg') }}">
                </div>
                <div class="col-md-4">
                    <h1>{{ offer.title }}</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <p>
            {{ offer.description | nl2br }}
        </p>
    </div>

    {% if offer.modalities %}
        <div class="container">

            <h2>Nos modalités d'inscription</h2>

            <div class="row flex">
                {% for modality in  offer.modalities %}
                    <div class="col-4">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ modality.title }}</h5>
                                <p class="card-text">Soit {{ modality.price }}€ par mois</p>
                                <a href="#" class="btn btn-primary">S'abonner</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% else %}
        <h2>Vous n'avez pas encore d'abonnements !</h2>
    {% endif %}
{% endblock %}